### ISSUE TITLE
[css] 15.用纯 CSS 创建一个三角形的原理是什么？

### ISSUE THREAD

**Issue by qiilee** [yisainan/web-interview#36]
答案：

```css
span {
  width: 0;
  height: 0;
  border-top: 40px solid transparent;
  border-left: 40px solid transparent;
  border-right: 40px solid transparent;
  border-bottom: 40px solid #ff0000;
}
```

![css_001](https://github.com/yisainan/web-interview/tree/master/images/css_001.jpg)
