### ISSUE TITLE
[兼容性] 18. CSS 透明度的设置

### ISSUE THREAD

**Issue by qiilee** [yisainan/web-interview#801]
问题说明：

1. 旧的 Opacity 设置

```css
#ceng {
  -khtml-opacity: 0.5;
  -moz-opacity: 0.5;
}
```

2. 在 Firefox, Safari, Chrome 和 Opera 下的 CSS 透明度

```css
#ceng {
  opacity: 0.7;
}
```

3. IE 下的 CSS 透明度

```css
#ceng {
  filter: alpha(opacity=40);
}
```

```css
#ceng {
  filter: progid:DXImageTransform.Microsoft.Alpha(opacity=40);
  /* 第一行在IE6, IE7和IE8下有效 */
  -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(opacity=40)";
  /*第二行仅在IE8下有效 */
}
```

解决方法：

```css
#ceng {
  filter: alpha(opacity=50);
  -moz-opacity: 0.5;
  -khtml-opacity: 0.5;
  opacity: 0.5;
}
```
