### ISSUE TITLE
[兼容性] 26. IE 与宽度和高度的问题

### ISSUE THREAD

**Issue by qiilee** [yisainan/web-interview#809]
问题说明：
IE 不认得 min-这个定义，但实际上它把正常的 width 和 height 当作有 min 的情况来使。这样问题就大了，如果只用宽度和高度，正常的浏览器里这两个值就不会变，如果只用 min-width 和 min-height 的话，IE 下面根本等于没有设置宽度和高度。

解决方法：
比如要设置背景图片，这个宽度是比较重要的。要解决这个问题，可以这样

```css
#box {
  width: 80px;
  height: 35px;
}
html > body #box {
  width: auto;
  height: auto;
  min-width: 80px;
  min-height: 35px;
}
```
