### ISSUE TITLE
[兼容性] 27. 页面的最小宽度

### ISSUE THREAD

**Issue by qiilee** [yisainan/web-interview#810]
如上一个问题，IE 不识别 min，要实现最小宽度，可用下面的方法：

```css
#container {
  min-width: 600px;
  width: expression(document.body.clientWidth < 600? "600px": "auto");
}
```

第一个 min-width 是正常的；但第 2 行的 width 使用了 Javascript，这只有 IE 才认得，这也会让你的 HTML 文档不太正规。它实际上通过 Javascript 的判断来实现最小宽度。
