### ISSUE TITLE
[兼容性] 28. DIV 浮动 IE 文本产生 3 象素的 bug

### ISSUE THREAD

**Issue by qiilee** [yisainan/web-interview#811]
左边对象浮动，右边采用外补丁的左边距来定位，右边对象内的文本会离左边有 3px 的间距.

```css
#box{ float:left; width:800px;}
#left{ float:left; width:50%;}
#right{ width:50%;}
html #left{ margin-right:-3px; //这句是关键}
```

```html
<div id="box">
  <div id="left">
    </div>
    <div id="right"></div></div>
  </div>
</div>
```
