### ISSUE TITLE
[兼容性] 30. 高度不适应

### ISSUE THREAD

**Issue by qiilee** [yisainan/web-interview#815]
问题说明：高度不适应是当内层对象的高度发生变化时外层高度不能自动进行调节，特别是当内层对象使用 margin 或 padding 时。

例：

```css
#box {}
#box p {
  margin-top: 20px;
  margin-bottom: 20px;
  text-align: center;
}
```

```html
<div id="box">
  <p>p对象中的内容</p>
</div>
```

解决办法：在 p 对象上下各加 2 个空的 div 对象 CSS 代码{height:0px;overflow:hidden;}或者为 div 加上 border 属性。
