### ISSUE TITLE
[兼容性] 33. 对齐文本与文本输入框

### ISSUE THREAD

**Issue by qiilee** [yisainan/web-interview#818]
加上 vertical-align:middle;

```css
<style type="text/css">
input {
    width:200px;
    height:30px;
    border:1px solid red;
    vertical-align:middle;
}
</style>
```

经验证，在 IE 下任一版本都不适用，而 ff、opera、safari、chrome 均 OK！
