### ISSUE TITLE
[兼容性] 34. LI 中内容超过长度后以省略号显示

### ISSUE THREAD

**Issue by qiilee** [yisainan/web-interview#819]
此技巧适用与 IE、Opera、safari、chrom 浏览器，FF 暂不支持。

```css
<style type="text/css">
li {
    width:200px;
    white-space:nowrap;
    text-overflow:ellipsis;
    -o-text-overflow:ellipsis;
    overflow: hidden;
}
</style>
```
