### ISSUE TITLE
[兼容性] 75. 单选框、复选框与后面的文字对不齐

### ISSUE THREAD

**Issue by qiilee** [yisainan/web-interview#937]
问题说明：
单选框、复选框与后面的文字对不齐。

解决方法：
```css
    .align{font-size:12px;}
    .align input{ display:block; float:left;}
    .align label{ display:block; float:left;padding-top:3px; padding-top:5px;}
```
